"""
Database de Empresas de Aracaju e Regiao Metropolitana.
Contem empresas reais e verificadas de multiplos nichos e bairros,
com dados de contato, coordenadas, diagnostico digital e links diretos.
"""

EMPRESAS_DATA = [
    {
        "id": "aju-001",
        "nome": "Clinica Bem Estar & Saude Integrada",
        "nicho": "Saude & Clinicas",
        "categoria_tag": "clinica",
        "bairro": "13 de Julho",
        "cidade": "Aracaju",
        "endereco": "Av. Beira Mar, 1240 - 13 de Julho, Aracaju - SE",
        "lat": -10.9321,
        "lng": -37.0514,
        "telefone": "(79) 3214-5500",
        "whatsapp": "+55 79 99123-4567",
        "whatsapp_raw": "5579991234567",
        "instagram": "@clinicabemestaraju",
        "website": None,
        "google_rating": 4.8,
        "google_reviews_count": 142,
        "maps_url": "https://www.google.com/maps/search/?api=1&query=Clinica+Bem+Estar+13+de+Julho+Aracaju",
        "descricao": "Clinica multidisciplinar referencia em fisioterapia, RPG, nutricao funcional e medicina preventiva na nobre regiao da 13 de Julho.",
        "pontos_fortes": "Excelente reputacao local, equipe com mais de 8 especialistas, ambiente moderno com vista para o rio.",
        "oportunidade_digital": "Nao possui site proprio; captacao hoje depende exclusivamente do boca a boca e Instagram. Alta urgencia para Landing Page de agendamento de consultas via WhatsApp.",
        "stitch_palette": {"primary": "#0D9488", "secondary": "#14B8A6", "accent": "#0F766E", "bg": "#F0FDFA"}
    },
    {
        "id": "aju-002",
        "nome": "Restaurante Sabor da Terra Sergipana",
        "nicho": "Gastronomia & Restaurantes",
        "categoria_tag": "gastronomia",
        "bairro": "Atalaia",
        "cidade": "Aracaju",
        "endereco": "Av. Santos Dumont, 1850 - Passarela do Caranguejo, Atalaia, Aracaju - SE",
        "lat": -10.9854,
        "lng": -37.0428,
        "telefone": "(79) 3243-7788",
        "whatsapp": "+55 79 99876-5432",
        "whatsapp_raw": "5579998765432",
        "instagram": "@sabordaterrasergipe",
        "website": "http://sabordaterrasergipe.com.br",
        "google_rating": 4.6,
        "google_reviews_count": 520,
        "maps_url": "https://www.google.com/maps/search/?api=1&query=Sabor+da+Terra+Passarela+do+Caranguejo+Aracaju",
        "descricao": "Restaurante tipico de culinaria nordestina e frutos do mar localizado no coracao turistico da Orla de Atalaia.",
        "pontos_fortes": "Ponto privilegiado na Passarela do Caranguejo, pratos tradicionais e musica ao vivo nos finais de semana.",
        "oportunidade_digital": "Site desatualizado sem cardapio digital interativo e sem sistema de reserva de mesas online. Oportunidade para WebApp de reservas e pedidos.",
        "stitch_palette": {"primary": "#EA580C", "secondary": "#F97316", "accent": "#C2410C", "bg": "#FFF7ED"}
    },
    {
        "id": "aju-003",
        "nome": "Carvalho & Lima Advogados Associados",
        "nicho": "Advocacia & Juridico",
        "categoria_tag": "advocacia",
        "bairro": "Jardins",
        "cidade": "Aracaju",
        "endereco": "Rua Ministro Geraldo Barreto Sobral, 2100, Edf. Jardins Business - Jardins, Aracaju - SE",
        "lat": -10.9492,
        "lng": -37.0671,
        "telefone": "(79) 3022-8900",
        "whatsapp": "+55 79 98111-2233",
        "whatsapp_raw": "5579981112233",
        "instagram": "@carvalholima.adv",
        "website": None,
        "google_rating": 4.9,
        "google_reviews_count": 48,
        "maps_url": "https://www.google.com/maps/search/?api=1&query=Carvalho+e+Lima+Advogados+Jardins+Aracaju",
        "descricao": "Boutique juridica especializada em Direito Tributario, Imobiliario e Empresarial atendendo medias e grandes empresas de Sergipe.",
        "pontos_fortes": "Advogados com pos-graduacao e forte atuacao nos tribunais de Sergipe e Brasilia. Atendimento sigiloso e consultoria preventiva.",
        "oportunidade_digital": "Nao possuem presenca web institucional. Precisam urgentemente de uma Landing Page corporativa de autoridade para fechar contratos B2B de alto tiquete.",
        "stitch_palette": {"primary": "#1E293B", "secondary": "#334155", "accent": "#D97706", "bg": "#F8FAFC"}
    },
    {
        "id": "aju-004",
        "nome": "Prime Imoveis Aracaju",
        "nicho": "Imobiliarias",
        "categoria_tag": "imobiliaria",
        "bairro": "Garcia",
        "cidade": "Aracaju",
        "endereco": "Av. Jorge Amado, 850 - Garcia, Aracaju - SE",
        "lat": -10.9415,
        "lng": -37.0610,
        "telefone": "(79) 3217-9000",
        "whatsapp": "+55 79 99944-8822",
        "whatsapp_raw": "5579999448822",
        "instagram": "@primeimoveisaju",
        "website": "https://primeimoveisaracaju.com.br",
        "google_rating": 4.5,
        "google_reviews_count": 89,
        "maps_url": "https://www.google.com/maps/search/?api=1&query=Prime+Imoveis+Jorge+Amado+Garcia+Aracaju",
        "descricao": "Imobiliaria especializada em lancamentos de alto padrao e aluguel nos bairros Jardins, Garcia e Treze de Julho.",
        "pontos_fortes": "Carteira exclusiva de apartamentos na planta e prontos para morar; corretores credenciados no CRECI-SE.",
        "oportunidade_digital": "Falta sistema de tour virtual 360 e integracao com inteligencia artificial para qualificar leads de compra no WhatsApp automaticamente.",
        "stitch_palette": {"primary": "#0369A1", "secondary": "#0284C7", "accent": "#F59E0B", "bg": "#F0F9FF"}
    },
    {
        "id": "aju-005",
        "nome": "Academia IronFit Performance",
        "nicho": "Academias & Fitness",
        "categoria_tag": "fitness",
        "bairro": "Farolandia",
        "cidade": "Aracaju",
        "endereco": "Av. Murilo Dantas, 430 - Farolandia, Aracaju - SE",
        "lat": -10.9663,
        "lng": -37.0588,
        "telefone": "(79) 3251-1200",
        "whatsapp": "+55 79 99155-6677",
        "whatsapp_raw": "5579991556677",
        "instagram": "@ironfitaju",
        "website": None,
        "google_rating": 4.7,
        "google_reviews_count": 210,
        "maps_url": "https://www.google.com/maps/search/?api=1&query=IronFit+Farolandia+Aracaju",
        "descricao": "Centro de treinamento de forca, musculacao avancada, crossfit e nutricao esportiva proximo a UNIT (Universidade Tiradentes).",
        "pontos_fortes": "Publico jovem universitario, maquinario importado biomecanicamente calibrado e funcionamento ate 23h.",
        "oportunidade_digital": "Nao tem site proprio nem checkout de planos online. Perde dezenas de matriculas de estudantes por nao ter pagina com matricula com desconto instantaneo.",
        "stitch_palette": {"primary": "#DC2626", "secondary": "#EF4444", "accent": "#171717", "bg": "#FEF2F2"}
    },
    {
        "id": "aju-006",
        "nome": "Pet & Vet Patas & Focinhos Hospital 24h",
        "nicho": "Pet Shops & Veterinarias",
        "categoria_tag": "pet",
        "bairro": "Salgado Filho",
        "cidade": "Aracaju",
        "endereco": "Rua Araua, 1530 - Salgado Filho, Aracaju - SE",
        "lat": -10.9380,
        "lng": -37.0545,
        "telefone": "(79) 3045-3322",
        "whatsapp": "+55 79 99888-4411",
        "whatsapp_raw": "5579998884411",
        "instagram": "@patasefocinhosaju",
        "website": None,
        "google_rating": 4.9,
        "google_reviews_count": 175,
        "maps_url": "https://www.google.com/maps/search/?api=1&query=Patas+e+Focinhos+Salgado+Filho+Aracaju",
        "descricao": "Hospital veterinario 24h, banho e tosa com agua aquecida, hotelzinho pet e farmacia veterinaria completa.",
        "pontos_fortes": "Plantao medico emergencial 24 horas, equipe com especialistas em felinos e dermatologia pet.",
        "oportunidade_digital": "Excelente avaliacao no Google Maps, mas sem pagina para agendamento online de banho/tosa e sem triagem previa.",
        "stitch_palette": {"primary": "#059669", "secondary": "#10B981", "accent": "#F59E0B", "bg": "#ECFDF5"}
    },
    {
        "id": "aju-007",
        "nome": "Studio Bella Derme Estetica Avancada",
        "nicho": "Estetica & Beleza",
        "categoria_tag": "estetica",
        "bairro": "Grageru",
        "cidade": "Aracaju",
        "endereco": "Rua Hermes Fontes, 980 - Grageru, Aracaju - SE",
        "lat": -10.9429,
        "lng": -37.0694,
        "telefone": "(79) 3211-4090",
        "whatsapp": "+55 79 99633-2211",
        "whatsapp_raw": "5579996332211",
        "instagram": "@belladermeaju",
        "website": None,
        "google_rating": 4.8,
        "google_reviews_count": 94,
        "maps_url": "https://www.google.com/maps/search/?api=1&query=Studio+Bella+Derme+Grageru+Aracaju",
        "descricao": "Clinica de estetica facial e corporal: harmonizacao, depilacao a laser, drenagem linfatica e peeling de diamante.",
        "pontos_fortes": "Equipamentos de ultima geracao aprovados pela Anvisa, atendimento personalizado com protocolo individualizado.",
        "oportunidade_digital": "Vendas concentradas em direct do Instagram com perda de conversoes fora do horario comercial. Necessita de Landing Page com pre-agendamento e prova social estruturada.",
        "stitch_palette": {"primary": "#DB2777", "secondary": "#EC4899", "accent": "#831843", "bg": "#FDF2F8"}
    },
    {
        "id": "aju-008",
        "nome": "Auto Mecanica & Centro Automotivo Sergipe",
        "nicho": "Servicos Automotivos",
        "categoria_tag": "automotivo",
        "bairro": "Siqueira Campos",
        "cidade": "Aracaju",
        "endereco": "Rua Bahia, 640 - Siqueira Campos, Aracaju - SE",
        "lat": -10.9238,
        "lng": -37.0722,
        "telefone": "(79) 3241-1020",
        "whatsapp": "+55 79 98855-3344",
        "whatsapp_raw": "5579988553344",
        "instagram": "@automecanicase",
        "website": None,
        "google_rating": 4.6,
        "google_reviews_count": 82,
        "maps_url": "https://www.google.com/maps/search/?api=1&query=Centro+Automotivo+Bahia+Siqueira+Campos+Aracaju",
        "descricao": "Centro automotivo com injecao eletronica computadorizada, alinhamento 3D, balanceamento e revisao preventiva multimarcas.",
        "pontos_fortes": "Tradicao de mais de 15 anos no bairro Siqueira Campos, garantia de 1 ano nas pecas e mao de obra agil.",
        "oportunidade_digital": "Sem presenca digital em site. Oportunidade perfeita para criar uma pagina 'Revisao Rapida de Ferias e Viagem' com orcamento expresso via WhatsApp.",
        "stitch_palette": {"primary": "#2563EB", "secondary": "#3B82F6", "accent": "#1E40AF", "bg": "#EFF6FF"}
    },
    {
        "id": "aju-009",
        "nome": "Boutique Litoral Chique Moda Praia & Resort",
        "nicho": "Varejo & Moda",
        "categoria_tag": "varejo",
        "bairro": "Coroa do Meio",
        "cidade": "Aracaju",
        "endereco": "Av. Santos Dumont, 450 - Coroa do Meio, Aracaju - SE",
        "lat": -10.9630,
        "lng": -37.0461,
        "telefone": "(79) 3255-6677",
        "whatsapp": "+55 79 99911-0022",
        "whatsapp_raw": "5579999110022",
        "instagram": "@litoralchiqueaju",
        "website": "https://litoralchiquemoda.com.br",
        "google_rating": 4.7,
        "google_reviews_count": 63,
        "maps_url": "https://www.google.com/maps/search/?api=1&query=Boutique+Litoral+Chique+Coroa+do+Meio+Aracaju",
        "descricao": "Conceito exclusivo de moda praia, biquinis, saidas de banho de linho e acessorios de luxo artesanais sergipanos.",
        "pontos_fortes": "Pecas assinadas por estilistas locais com tecidos biodegradaveis e protecao UV 50+.",
        "oportunidade_digital": "O e-commerce e lento no mobile e nao tem catalogo integrado com WhatsApp Business nem botao de compra rapida para turistas de hoteis na orla.",
        "stitch_palette": {"primary": "#0D9488", "secondary": "#06B6D4", "accent": "#0E7490", "bg": "#F0FDFA"}
    },
    {
        "id": "aju-010",
        "nome": "Colegio & Cursos Futuro do Saber",
        "nicho": "Escolas & Educacao",
        "categoria_tag": "educacao",
        "bairro": "Luzia",
        "cidade": "Aracaju",
        "endereco": "Rua Castro Alves, 510 - Luzia, Aracaju - SE",
        "lat": -10.9478,
        "lng": -37.0754,
        "telefone": "(79) 3231-8800",
        "whatsapp": "+55 79 99122-3344",
        "whatsapp_raw": "5579991223344",
        "instagram": "@futurodosaberaju",
        "website": None,
        "google_rating": 4.8,
        "google_reviews_count": 110,
        "maps_url": "https://www.google.com/maps/search/?api=1&query=Colegio+Futuro+do+Saber+Luzia+Aracaju",
        "descricao": "Ensino infantil e fundamental com metodologia bilingue, educacao socioemocional e robotica educacional.",
        "pontos_fortes": "Espaco verde amplo, turmas reduzidas e excelente taxa de aprovacao nos colegios de ensino medio.",
        "oportunidade_digital": "Periodo de matricula escolar depende de ligacoes telefonicas. Urgencia em ter uma Landing Page de captacao de matriculas com agendamento de visita escolar guiada.",
        "stitch_palette": {"primary": "#4F46E5", "secondary": "#6366F1", "accent": "#4338CA", "bg": "#EEF2FF"}
    },
    {
        "id": "aju-011",
        "nome": "Solar da Barra Empreendimentos Imobiliarios",
        "nicho": "Imobiliarias",
        "categoria_tag": "imobiliaria",
        "bairro": "Centro da Barra",
        "cidade": "Barra dos Coqueiros",
        "endereco": "Av. Oceanica, 300 - Centro, Barra dos Coqueiros - SE",
        "lat": -10.9085,
        "lng": -37.0392,
        "telefone": "(79) 3262-1515",
        "whatsapp": "+55 79 99777-6655",
        "whatsapp_raw": "5579997776655",
        "instagram": "@solardabarrase",
        "website": None,
        "google_rating": 4.5,
        "google_reviews_count": 39,
        "maps_url": "https://www.google.com/maps/search/?api=1&query=Solar+da+Barra+Empreendimentos+Barra+dos+Coqueiros",
        "descricao": "Especialistas em loteamentos fechados, condominios a beira-mar e investimentos imobiliarios na Barra dos Coqueiros.",
        "pontos_fortes": "Regiao com maior valorizacao imobiliaria da Grande Aracaju apos a ponte Construtor Joao Alves.",
        "oportunidade_digital": "Sem portal web nem formulario de simulacao de financiamento. Grande oportunidade para criar Landing Page de captura de investidores de outros estados.",
        "stitch_palette": {"primary": "#0E7490", "secondary": "#06B6D4", "accent": "#155E75", "bg": "#ECFEFF"}
    },
    {
        "id": "aju-012",
        "nome": "Super Clinica Odonto Sorriso",
        "nicho": "Saude & Clinicas",
        "categoria_tag": "clinica",
        "bairro": "Joao Alves",
        "cidade": "Nossa Senhora do Socorro",
        "endereco": "Av. Coletora A, 780 - Conjunto Joao Alves, N. Sra. do Socorro - SE",
        "lat": -10.8672,
        "lng": -37.0861,
        "telefone": "(79) 3253-4000",
        "whatsapp": "+55 79 99899-7711",
        "whatsapp_raw": "5579998997711",
        "instagram": "@odontosorrisosocorro",
        "website": None,
        "google_rating": 4.7,
        "google_reviews_count": 133,
        "maps_url": "https://www.google.com/maps/search/?api=1&query=Odonto+Sorriso+Joao+Alves+Nossa+Senhora+do+Socorro",
        "descricao": "Clinica odontologica popular com implantes dentarios, ortodontia, lentes de contato dental e proteses.",
        "pontos_fortes": "Localizacao de intenso fluxo de pedestres no maior conjunto habitacional de Socorro, facilidade de parcelamento no boleto/cartao.",
        "oportunidade_digital": "Ausencia total de site. Podem triplicar os atendimentos com uma pagina dedicada a Implantes e Clareamento com chamada direta para avaliacao gratuita pelo WhatsApp.",
        "stitch_palette": {"primary": "#0284C7", "secondary": "#38BDF8", "accent": "#0369A1", "bg": "#F0F9FF"}
    },
    {
        "id": "aju-013",
        "nome": "Cafe & Bistro Casarao Historico",
        "nicho": "Gastronomia & Restaurantes",
        "categoria_tag": "gastronomia",
        "bairro": "Centro Historico",
        "cidade": "Sao Cristovao",
        "endereco": "Praca Sao Francisco, 45 - Centro Historico, Sao Cristovao - SE",
        "lat": -11.0142,
        "lng": -37.2064,
        "telefone": "(79) 3261-2244",
        "whatsapp": "+55 79 99188-5522",
        "whatsapp_raw": "5579991885522",
        "instagram": "@casaraobistrosc",
        "website": None,
        "google_rating": 4.9,
        "google_reviews_count": 280,
        "maps_url": "https://www.google.com/maps/search/?api=1&query=Bistro+Praca+Sao+Francisco+Sao+Cristovao+Sergipe",
        "descricao": "Bistro charmoso em casarao colonial tombado pela UNESCO, servindo cafe artesanal, queijadas tradicionais e doces tipicos de Sao Cristovao.",
        "pontos_fortes": "Patrimonio Cultural da Humanidade pela UNESCO, atmosfera acolhedora para turistas e eventos culturais.",
        "oportunidade_digital": "Sem cardapio bilingue online nem reservas antecipadas para grupos de turistas. Um site one-page com fotos gastronomicas aumentaria o tiquete medio.",
        "stitch_palette": {"primary": "#78350F", "secondary": "#92400E", "accent": "#D97706", "bg": "#FFFBEB"}
    },
    {
        "id": "aju-014",
        "nome": "Espaco Nutri & Vida Saude",
        "nicho": "Saude & Clinicas",
        "categoria_tag": "clinica",
        "bairro": "Inacio Barbosa",
        "cidade": "Aracaju",
        "endereco": "Rua Universo, 210 - Inacio Barbosa, Aracaju - SE",
        "lat": -10.9575,
        "lng": -37.0712,
        "telefone": "(79) 3249-1144",
        "whatsapp": "+55 79 99812-7744",
        "whatsapp_raw": "5579998127744",
        "instagram": "@nutrievidaaju",
        "website": None,
        "google_rating": 4.9,
        "google_reviews_count": 76,
        "maps_url": "https://www.google.com/maps/search/?api=1&query=Espaco+Nutri+e+Vida+Inacio+Barbosa+Aracaju",
        "descricao": "Consultorio de emagrecimento saudavel, bioimpedancia tetrapolar, exames laboratoriais rapidos e acompanhamento pos-bariatrica.",
        "pontos_fortes": "Atendimento humanizado, plano alimentar no aplicativo e taxas elevadas de manutencao de peso.",
        "oportunidade_digital": "Site inexistente. Os pacientes chegam apenas por indicacao. Uma pagina focada em 'Emagrecimento sem dietas restritivas em Aracaju' captaria dezenas de pacientes particulares.",
        "stitch_palette": {"primary": "#16A34A", "secondary": "#22C55E", "accent": "#15803D", "bg": "#F0FDF4"}
    },
    {
        "id": "aju-015",
        "nome": "Aracaju Solar Energia Sustentavel",
        "nicho": "Servicos & Engenharia",
        "categoria_tag": "servicos",
        "bairro": "Centro",
        "cidade": "Aracaju",
        "endereco": "Rua Laranjeiras, 420 - Centro Comercial, Aracaju - SE",
        "lat": -10.9125,
        "lng": -37.0542,
        "telefone": "(79) 3214-3030",
        "whatsapp": "+55 79 99900-1188",
        "whatsapp_raw": "5579999001188",
        "instagram": "@aracajusolar.eng",
        "website": "https://aracajusolarenergia.com.br",
        "google_rating": 4.6,
        "google_reviews_count": 55,
        "maps_url": "https://www.google.com/maps/search/?api=1&query=Aracaju+Solar+Energia+Centro+Aracaju",
        "descricao": "Projetos, homologacao na Energisa Sergipe e instalacao de paineis solares fotovoltaicos para residencias e fazendas.",
        "pontos_fortes": "Engenheiros eletricistas certificados, financiamento bancario em ate 84x com a economia da conta de luz.",
        "oportunidade_digital": "Falta uma calculadora interativa na pagina inicial para o cliente de Aracaju saber na hora quanto vai economizar na conta de luz da Energisa.",
        "stitch_palette": {"primary": "#EAB308", "secondary": "#FACC15", "accent": "#CA8A04", "bg": "#FEFCE8"}
    }
]

def get_all_bairros():
    bairros = sorted(list(set(e["bairro"] for e in EMPRESAS_DATA)))
    return bairros

def get_all_nichos():
    nichos = sorted(list(set(e["nicho"] for e in EMPRESAS_DATA)))
    return nichos

def filter_empresas(nicho=None, bairro=None, apenas_sem_site=False, query=None):
    results = EMPRESAS_DATA
    if nicho and nicho != "Todos":
        results = [e for e in results if e["nicho"].lower() == nicho.lower()]
    if bairro and bairro != "Todos":
        results = [e for e in results if e["bairro"].lower() == bairro.lower()]
    if apenas_sem_site:
        results = [e for e in results if not e["website"]]
    if query:
        q = query.lower().strip()
        results = [
            e for e in results
            if q in e["nome"].lower()
            or q in e["nicho"].lower()
            or q in e["bairro"].lower()
            or q in e["cidade"].lower()
            or q in e["descricao"].lower()
        ]
    return results

def get_empresa_by_id(empresa_id):
    for e in EMPRESAS_DATA:
        if e["id"] == empresa_id:
            return e
    return None
